### ISSUE TITLE
No HMR / 404 on client requests

### ISSUE THREAD

**Issue by astahmer** [jrestall/remix-kit#13]
### Describe the bug

hey, I followed the instructions in https://github.com/jrestall/remix-kit/blob/main/CONTRIBUTING.md and this happens when visiting localhost:3000

at first I tried just cloning the playground/react-app folder and removing workspace/project references + using packages from npm but I had this issue so I thought of trying in the remix-kit repo directly

have I missed something ?
pnpm i / pnpm build:stub / cd playground/react-app / pnpm dev

in the console it looks like

<img width="1119" alt="Screenshot 2022-12-28 at 11 54 43" src="https://user-images.githubusercontent.com/47224540/209801662-68fd3ce3-359e-4d48-9b4c-003d5c720e1c.png">

and in the network tab

![Screenshot 2022-12-28 at 11 54 33](https://user-images.githubusercontent.com/47224540/209801617-56be6714-c924-4d07-b034-60b5799ebc64.png)
ex: the first error is on the url
http://localhost:3000/Users/astahmer/dev/open-source/remix-kit/playground/react-app/app/entry.client.tsx

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/jrestall/remix-kit/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/jrestall/remix-kit/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a RemixKit issue and not a Remix specific issue. For example, if it's a Remix related bug, it should likely be reported to [remix](https://github.com/remix-run/remix) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/jrestall/remix-kit/discussions).

**Comment by astahmer** [comment]
I didnt link a reproduction since it's directly in the `remix-kit` repo but I have this PR from my first try using remix-kit with just the playground/react-app folder clone that I mentioned earlier

https://github.com/astahmer/box-extractor/pull/17

**Comment by jrestall** [comment]
Hi @astahmer, can you please confirm if you made sure to build the remix-react package rather than stub that with jiti which currently doesn't work but I'm working on fixing once the ReactRefresh component is injected rather than referenced.

> If using stubs it doesn't currently work if the remix-react package has been stubbed, so you need to cd to packages/remix-react and run pnpm run prepack so that just that package isn't using jiti.

**Comment by astahmer** [comment]
sorry, I hadnt. I just did tho and it didnt seem to change anything
`cd packages/remix-react` / `pnpm prepack` / `cd ../../playground/react-app/` / `pnpm dev`

**Comment by jrestall** [comment]
I think the issue could be you are visiting localhost:3000 directly which is the Remix App server. The Dev server is at localhost:3005. Hitting the Remix server directly during dev won't work as Remix doesn't understand how to serve typescript files directly like Vite does.

**Comment by astahmer** [comment]
yes indeed ! I'm visiting localhost:3000, thought it was the right one since localhost:3005 throws a 500 for me 🥲 
```json
{
  "statusCode": 500,
  "stack": []
}
```

```
                                                                                                                                                                 12:51:45
ℹ Runner started on http://localhost:3000                                                                                                                         12:51:45
✔ Remix server ready in 312.943ms                                                                                                                                 12:51:45

ℹ Document request (/)                                                                                                                                            12:51:48

 ERROR  [h3] [unhandled] fetch is not defined                                                                                                                     12:51:48

  at Object.handler (/Users/astahmer/dev/open-source/remix-kit/packages/remix-vite/src/vite-node.ts:142:7)
  at Object.handler (/Users/astahmer/dev/open-source/remix-kit/node_modules/.pnpm/h3@1.0.2/node_modules/h3/dist/index.mjs:723:31)
  at async toNodeHandle (/Users/astahmer/dev/open-source/remix-kit/node_modules/.pnpm/h3@1.0.2/node_modules/h3/dist/index.mjs:798:7)

ℹ Document request (/favicon.ico)    
```

maybe there's another package that I should build before ?

**Comment by jrestall** [comment]
That one could be on me, I'm using the internal nodejs fetch implementation which is only available in nodejs 17.5+. What version are you using? I should probably use @remix-run/web-fetch instead for better support.

**Comment by astahmer** [comment]
❯ node -v
v16.14.0

I should also upgrade 😅

**Comment by jrestall** [comment]
Yes that should fix it but I appreciate the bug report and will leave this open as a reminder to not use the built-in implementation yet. This would also make a good first issue for anyone wanting to contribute.

**Comment by jrestall** [comment]
Should be fixed once this commit is released https://github.com/jrestall/remix-kit/commit/155741ee9b9fb0b037ff500d1359ea745951b4a5

**Comment by jrestall** [comment]
Hi @astahmer, please reopen if v0.2.1 doesn't fix this. I moved to using https://github.com/unjs/node-fetch-native to provide better backwards compatibility.
